# Generated by Django 3.2.9 on 2022-02-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_alias', models.SlugField(help_text='Defines the model slug to be used in HTTP requests')),
                ('map_file', models.FileField(help_text='The associated map file', unique=True, upload_to='')),
                ('map_type', models.CharField(choices=[('ori', 'Orientation map'), ('dir', 'Direction map')], help_text='Whether the map is orientational or diractional', max_length=3)),
            ],
        ),
    ]
