# Generated by Django 3.2.9 on 2022-03-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.SlugField(help_text='Defines the model slug to be used in HTTP requests', unique=True)),
                ('data', models.FileField(help_text='The associated map file', unique=True, upload_to='')),
                ('type', models.CharField(choices=[('ori', 'Orientation map'), ('dir', 'Direction map')], help_text='Whether the map is orientational or directional', max_length=3)),
                ('resolution_x', models.PositiveIntegerField(blank=True, help_text='Map width, px', null=True)),
                ('resolution_y', models.PositiveIntegerField(blank=True, help_text='Map height, px', null=True)),
                ('width', models.FloatField(blank=True, help_text='Map width, um', null=True)),
                ('height', models.FloatField(blank=True, help_text='Map height, um', null=True)),
            ],
        ),
    ]
