# Generated by Django 3.2.9 on 2022-01-16 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_fill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cookie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(help_text='Token hash given to that user', max_length=256)),
                ('expiration_date', models.DateTimeField(help_text='Cookie also have some short amount of life defined by a the server system administrator')),
                ('user', models.ForeignKey(help_text='Actual corefacility user that have this cookie', on_delete=django.db.models.deletion.CASCADE, related_name='cookie', to='core.user')),
            ],
        ),
    ]
