# Generated by Django 4.2.5 on 2024-08-20 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_application', '0003_labjournal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labjournalrecord',
            name='datetime',
            field=models.DateTimeField(db_index=True, help_text='Date and time of the start of event', null=True),
        ),
        migrations.AlterField(
            model_name='labjournalrecord',
            name='name',
            field=models.CharField(db_index=True, help_text='Head of the service record (if applicable)', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='labjournalrecord',
            name='parent_category',
            field=models.ForeignKey(help_text='Parent category or NULL if root', null=True, on_delete=django.db.models.deletion.RESTRICT, to='core_application.labjournalrecord'),
        ),
    ]
