# Generated by Django 3.2.9 on 2021-12-06 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imaging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RectangularRoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left', models.PositiveIntegerField(help_text='ROI left border')),
                ('right', models.PositiveIntegerField(help_text='ROI right border')),
                ('top', models.PositiveIntegerField(help_text='ROI top border')),
                ('bottom', models.PositiveIntegerField(help_text='ROI bottom border')),
                ('map', models.ForeignKey(help_text='A map to which this ROI is attached', on_delete=django.db.models.deletion.CASCADE, related_name='rectangular_roi', to='imaging.map')),
            ],
        ),
        migrations.CreateModel(
            name='Pinwheel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveBigIntegerField(help_text='pinwheel abscissa, px')),
                ('y', models.PositiveBigIntegerField(help_text='pinwheel ordinate, px')),
                ('map', models.ForeignKey(help_text='A map to which this ROI is attached', on_delete=django.db.models.deletion.CASCADE, related_name='pinwheels', to='imaging.map')),
            ],
        ),
    ]
