"""
Django settings for corefacility project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import Path




# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators




# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
