from .main_window import MainWindow

from .authorize import AuthorizationView
from .user import UserViewSet
from .group import GroupViewSet
from .project import ProjectViewSet
from .access_level import AccessLevelView
from .permission_viewset import PermissionViewSet
from .login import LoginView
from .profile import ProfileView
from .synchronization_view import SynchronizationView
from .log import LogViewSet
from .log_record import LogRecordViewSet
from .widgets import WidgetsView
from .view_404 import View404
from .projects_module_list_view import ProjectModulesListView
from .profile_avatar import ProfileAvatarView
from .module_settings import ModuleSettingsViewSet
from .entry_point_list import EntryPointListView
from .authorization_method_setup import AuthorizationMethodSetupView
