# Generated by Django 4.2.5 on 2023-10-06 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, help_text='The user E-mail when he registered in the Mail.ru system', max_length=254, unique=True)),
                ('user', models.OneToOneField(help_text='corefacility user to which this account is attached', on_delete=django.db.models.deletion.CASCADE, related_name='mailru_account', to='core_application.user')),
            ],
        ),
    ]
