# Generated by Django 3.2.9 on 2021-12-07 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, help_text='The user e-mail as typed for the IHNA personal page', max_length=254, unique=True)),
                ('user', models.ForeignKey(help_text='The corefacility user to which ihna account is attached', on_delete=django.db.models.deletion.CASCADE, related_name='ihna_account', to='core.user')),
            ],
        ),
    ]
