# Generated by Django 3.2.9 on 2021-12-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrypoint',
            name='type',
            field=models.CharField(choices=[('lst', 'As list (the user can enable arbitrary amount of modules in this entry point)'), ('sel', 'As select (the user must choice which module in this entry point to enable)')], default='lst', editable=False, help_text='Whether the entry point looks like list or select?', max_length=3),
        ),
    ]
