from datetime import timedelta

from ru.ihna.kozhukhov.core_application.exceptions.entity_exceptions import EntityFieldInvalid, \
    EntityOperationNotPermitted, EntityDuplicatedException

ALIAS_MAX_CHARS = 64
NAME_MAX_CHARS=256
COMMENTS_MAX_CHARS = 1_000

def labjournal_record_provider():
    """
    Test cases for the labjournal_record.record.Record entity
    """
    return [
        (None, 0, 'optical_imaging', None, None,
            None, 'leader', 'leader', 'category', COMMENTS_MAX_CHARS*'Я'),
        ('no_root', 3, 'the_rabbit_project', ALIAS_MAX_CHARS*'A', 'year',
            True, 'leader', 'no_leader', 'data', ALIAS_MAX_CHARS*'Z'),
        ('no_root', 2, 'optical_imaging', 'sample_record', 'day',
            False, 'no_leader', 'leader', 'service', 'Я'),
        ('no_root', 3, 'optical_imaging', 'A', 'inf',
            True, 'leader', 'leader', 'service', None),
        ('root', 1, 'optical_imaging', 'max_chars', 'day',
            True, 'leader', 'leader', 'data', 'Пример комментариев к записи'),
        ('no_root', 2, 'the_rabbit_project', 'sample_record', 'year',
            True, 'leader', 'leader', 'category', 'Я'),
        ('root', 1, 'the_rabbit_project', 'sample_record', 'day',
            True, 'leader', 'no_leader', 'category', None),
        ('no_root', 2, 'the_rabbit_project', 'A', 'hour',
            False, 'no_leader', 'leader', 'data', 'Я'),
        ('no_root', 2, 'the_rabbit_project', 'A'*ALIAS_MAX_CHARS, 'inf',
            False, 'no_leader', 'leader', 'category', None),
        ('no_root', 3, 'optical_imaging', 'sample_record', 'inf',
            False, 'no_leader', 'no_leader', 'data', 'Я'),
        ('no_root', 2, 'optical_imaging', 'sample_record', 'hour',
            True, 'leader', 'no_leader', 'service', 'Я'*ALIAS_MAX_CHARS),
        ('root', 1, 'the_rabbit_project', 'A'*ALIAS_MAX_CHARS, 'year',
            True, 'leader', 'no_leader', 'service', 'Я'),
        (None, 0, 'the_rabbit_project', None, None,
            None, 'leader', 'leader', 'category', 'Я'),
        ('no_root', 3, 'the_rabbit_project', 'A'*ALIAS_MAX_CHARS, 'hour',
            True, 'leader', 'leader', 'data', 'Я'*COMMENTS_MAX_CHARS),
        ('no_root', 2, 'optical_imaging', 'A'*ALIAS_MAX_CHARS, 'year',
            False, 'no_leader', 'no_leader', 'data', None),
        (None, 0, 'the_rabbit_project', None, None,
            None, 'leader', 'leader', 'category', None),
        ('no_root', 2, 'the_rabbit_project', 'sample_record', 'inf',
            True, 'leader', 'no_leader', 'service', 'Пример комментариев к лабораторной записи'),
        (None, 0, 'optical_imaging', None, None,
            None, 'leader', 'leader', 'category', ALIAS_MAX_CHARS*'Z'),
        ('root', 1, 'the_rabbit_project', 'sample_record', 'inf',
            False, 'no_leader', 'no_leader', 'service', COMMENTS_MAX_CHARS*'Я'),
        ('no_root', 3, 'the_rabbit_project', 'sample_record', 'hour',
            False, 'no_leader', 'leader', 'category', None),
        (None, 0, 'optical_imaging', None, None,
            None, 'leader', 'leader', 'category', 'Пример комментариев к записи в лабораторном журнале'),
        ('no_root', 3, 'the_rabbit_project', 'A', 'day',
            True, 'leader', 'leader', 'data', ALIAS_MAX_CHARS*'A'),
        ('root', 1, 'optical_imaging', 'A', 'year',
            False, 'no_leader', 'leader', 'data', 'Пример комментариев к лабораторной записи'),
        ('no_root', 2, 'optical_imaging', 'A', 'day',
            True, 'leader', 'no_leader', 'service', COMMENTS_MAX_CHARS*'Я'),
        ('no_root', 2, 'optical_imaging', 'sample_record', 'year',
            False, 'no_leader', 'leader', 'category', 'Я'*COMMENTS_MAX_CHARS),
        ('root', 1, 'the_rabbit_project', 'A', 'inf',
            False, 'no_leader', 'no_leader', 'category', 'Я'*ALIAS_MAX_CHARS),
        ('no_root', 3, 'the_rabbit_project', 'sample_record', 'day',
            False, 'no_leader', 'no_leader', 'category', 'Пример комментариев к лабораторной записи'),
        ('root', 1, 'optical_imaging', 'A', 'day',
            False, 'no_leader', 'leader', 'service', 'Я'*ALIAS_MAX_CHARS),
    ]


def parent_category_change_provider():
    return [
        ('root', 1, 'the_rabbit_project', 'no_leader', False, 'data', 'no_root', 2, 'optical_imaging', 'on_create',
            True, False),
        (None, 0, 'optical_imaging', 'leader', False, 'category', 'root', 1, 'the_rabbit_project', 'after_create',
            AttributeError, None),
        ('no_root', 2, 'the_rabbit_project', 'leader', True, 'service', 'no_root', 2, 'the_rabbit_project', 'after_load',
            EntityOperationNotPermitted, True),
        ('no_root', 3, 'optical_imaging', 'no_leader', True, 'service', 'no_root', 2, 'optical_imaging', 'after_create',
            EntityOperationNotPermitted, False),
        ('no_root', 2, 'optical_imaging', 'no_leader', True, 'data', None, 0, 'the_rabbit_project', 'on_create',
            EntityFieldInvalid, None),
        ('no_root', 3, 'the_rabbit_project', 'no_leader', False, 'category', 'no_root', 3, 'optical_imaging', 'after_load',
            EntityOperationNotPermitted, False),
        ('no_root', 3, 'the_rabbit_project', 'leader', False, 'category', None, 0, 'optical_imaging', 'after_load',
            EntityFieldInvalid, None),
        ('no_root', 3, 'optical_imaging', 'no_leader', True, 'data', 'root', 1, 'the_rabbit_project', 'after_load',
            EntityOperationNotPermitted, False),
        ('root', 1, 'the_rabbit_project', 'leader', True, 'service', None, 0, 'the_rabbit_project', 'after_create',
            EntityFieldInvalid, None),
        (None, 0, 'the_rabbit_project', 'leader', False, 'category', None, 0, 'optical_imaging', 'after_load',
            AttributeError, None),
        (None, 0, 'optical_imaging', 'leader', False, 'category', 'no_root', 2, 'optical_imaging', 'on_create',
            AttributeError, None),
        ('root', 1, 'optical_imaging', 'no_leader', False, 'service', 'root', 1, 'optical_imaging', 'on_create',
            True, False),
        ('root', 1, 'optical_imaging', 'leader', True, 'data', 'no_root', 3, 'the_rabbit_project', 'after_create',
            EntityOperationNotPermitted, True),
        ('no_root', 2, 'the_rabbit_project', 'no_leader', False, 'category', 'no_root', 3, 'optical_imaging', 'after_create',
            EntityOperationNotPermitted, False),
        (None, 0, 'the_rabbit_project', 'leader', False, 'category', 'no_root', 3, 'the_rabbit_project', 'on_create',
            AttributeError, None),
        ('root', 1, 'the_rabbit_project', 'no_leader', True, 'category', 'root', 1, 'the_rabbit_project', 'after_load',
            EntityOperationNotPermitted, False),
        ('no_root', 2, 'optical_imaging', 'no_leader', True, 'service', 'root', 1, 'optical_imaging', 'on_create',
            True, False),
        ('no_root', 2, 'optical_imaging', 'no_leader', False, 'service', 'no_root', 3, 'the_rabbit_project', 'on_create',
            True, False),
    ]


def alias_change_provider():
    return [
        ('no_root', 2, 'category', 'optical/123', 'after_load', EntityFieldInvalid),
        ('root', 1, 'category', 'optical', 'on_creating', None),
        ('no_root', 2, 'data', 'Optical Imaging', 'on_creating', EntityFieldInvalid),
        ('no_root', 2, 'data', 'optical-123', 'after_load', None),
        ('root', 1, 'data', 'sample_category', 'after_load', None),
        ('no_root', 2, 'category', 'a1', 'after_load', EntityFieldInvalid),
        ('no_root', 2, 'category', 'a1', 'on_creating', EntityDuplicatedException),
        ('no_root', 3, 'data', 'optical/123', 'on_creating', EntityFieldInvalid),
        ('no_root', 3, 'category', 'оптический', 'on_creating', EntityFieldInvalid),
        (None, 0, 'category', 'optical', 'after_load', AttributeError),
        ('root', 1, 'data', 'Optical123', 'after_load', None),
        ('no_root', 2, 'data', 'оптический', 'on_creating', EntityFieldInvalid),
        ('root', 1, 'category', 'Optical Imaging', 'after_load', EntityFieldInvalid),
        ('root', 1, 'category', None, 'on_creating', EntityFieldInvalid),
        ('no_root', 2, 'data', 'optical\\123', 'after_load', EntityFieldInvalid),
        ('no_root', 3, 'service', 'optical', 'on_creating', AttributeError),
        ('no_root', 3, 'category', 'Optical123', 'on_creating', None),
        ('no_root', 2, 'data', 'a', 'after_load', None),
        ('no_root', 3, 'category', 'sample_category', 'on_creating', None),
        ('no_root', 3, 'category', 'optical_123', 'after_load', None),
        ('no_root', 3, 'data', None, 'after_load', EntityFieldInvalid),
        ('no_root', 2, 'category', 'Optical123', 'after_load', None),
        ('no_root', 2, 'service', 'optical', 'after_load', AttributeError),
        ('no_root', 3, 'category', 'a', 'on_creating', None),
        ('root', 1, 'data', 'a', 'after_load', EntityFieldInvalid),
        ('no_root', 3, 'category', 'optical\\123', 'on_creating', EntityFieldInvalid),
        ('no_root', 3, 'category', 'optical-123', 'on_creating', None),
        ('root', 1, 'data', 'optical/123', 'after_load', EntityFieldInvalid),
        ('root', 1, 'data', 'a1', 'on_creating', None),
        ('root', 1, 'category', 'оптический', 'on_creating', EntityFieldInvalid),
        ('no_root', 2, 'data', 'sample_category', 'on_creating', EntityDuplicatedException),
        ('root', 1, 'category', 'optical.123', 'after_load', EntityFieldInvalid),
        ('root', 1, 'data', 'optical_123', 'on_creating', None),
        ('no_root', 2, 'data', 'optical.123', 'on_creating', EntityFieldInvalid),
        ('no_root', 2, 'data', None, 'after_load', EntityFieldInvalid),
        ('no_root', 3, 'data', 'optical.123', 'after_load', EntityFieldInvalid),
        ('no_root', 2, 'data', 'optical_123', 'on_creating', None),
        ('root', 1, 'data', 'optical\\123', 'on_creating', EntityFieldInvalid),
        ('no_root', 3, 'category', 'a1', 'on_creating', None),
        ('no_root', 3, 'data', 'Optical Imaging', 'on_creating', EntityFieldInvalid),
        ('root', 1, 'category', 'optical-123', 'after_load', None),
        ('root', 1, 'service', 'optical', 'on_creating', AttributeError),
        (None, 0, 'category', 'optical', 'on_creating', AttributeError),
        ('no_root', 2, 'data', 'optical', 'after_load', None),
    ]


def datetime_change_provider():
    return [
        ('no_root', 3, 'data', '-day', 'after_create',
            None, "2012-07-14 02:30", "2012-07-14 02:30", "2012-07-14 02:30", timedelta()),
        ('no_root', 2, 'data', '+inf', 'on_creating',
            None, '2033-11-09 00:00', '2024-01-01 00:00', '2033-11-09 00:00', timedelta(days=3600)),
        (None, 0, 'category', '0', 'on_creating',
            ValueError, None, None, None, None),
        ('no_root', 2, 'service', '0', 'after_create',
            None, '2024-01-01 0:00', '2024-01-01 0:00', '2024-01-02 0:00', timedelta()),
        ('no_root', 3, 'service', '+inf', 'on_creating',
            None, '2022-05-24 12:30', '2022-05-24 12:30', '2022-05-24 12:30', timedelta()),
        (None, 0, 'category', '+day', 'after_create',
            ValueError, None, None, None, None),
        ('no_root', 3, 'category', '0', 'after_create',
            ValueError, None, None, None, None),
        ('no_root', 3, 'category', '0', 'after_create',
            ValueError, None, None, None, None),
        (None, 0, 'category', '-hour', 'after_create',
            ValueError, None, None, None, None),
        ('root', 1, 'data', '0', 'after_create',
            None, '2012-07-15 12:30', None, None, None),
        ('root', 1, 'service', '-hour', 'on_creating',
            None, '2012-07-15 11:20', None, None, None),
        ('no_root', 2, 'category', '+year', 'after_create',
            ValueError, None, None, None, None),
        ('no_root', 2, 'data', '+day', 'on_creating',
            None, '2024-01-02 10:00', '2024-01-01 0:00', '2024-01-02 10:00', timedelta(days=1, hours=10)),
        ('no_root', 2, 'service', '-day', 'on_creating',
            None, '2023-12-30 14:00', '2023-12-30 14:00', '2024-01-02 0:00', timedelta()),
        ('no_root', 3, 'service', '-year', 'after_create',
            None, '2011-07-15 12:30', '2011-07-15 12:30', '2011-07-15 12:30', timedelta()),
        ('no_root', 2, 'data', '-year', 'on_creating',
            None, '2022-12-31 00:00', '2022-12-31 00:00', '2024-01-02 00:00', timedelta()),
        (None, 0, 'category', '+year', 'on_creating',
            ValueError, None, None, None, None),
        ('no_root', 2, 'data', '-hour', 'on_creating',
            None, '2023-12-31 22:50', '2023-12-31 22:50', '2024-01-02 00:00', timedelta()),
        ('root', 1, 'category', str, 'on_creating',
            ValueError, None, None, None, None),
        ('no_root', 3, 'service', str, 'after_create',
            EntityFieldInvalid, None, None, None, None),
        ('no_root', 2, 'data', '+hour', 'after_create',
            None, '2024-01-01 01:10', '2024-01-01 00:00', '2024-01-02 00:00', timedelta(hours=1, minutes=10)),
        ('root', 1, 'category', '-day', 'after_create',
            ValueError, None, None, None, None),
        ('no_root', 3, 'service', '+day', 'on_creating',
            None, '2012-07-16 22:30', '2012-07-16 22:30', '2012-07-16 22:30', timedelta()),
        (None, 0, 'category', '-day', 'on_creating',
            ValueError, None, None, None, None),
        ('root', 1, 'service', '+hour', 'on_creating',
            None, '2012-07-15 13:40', None, None, None),
        ('no_root', 3, 'category', '+hour', 'after_create',
            ValueError, None, None, None, None),
        (None, 0, 'category', '+hour', 'on_creating',
            ValueError, None, None, None, None),
        ('root', 1, 'category', '+day', 'after_create',
            ValueError, None, None, None, None),
        (None, 0, 'category', '+inf', 'after_create',
            ValueError, None, None, None, None),
        ('root', 1, 'service', '+year', 'on_creating',
            None, '2013-07-16 12:30', None, None, None),
        ('no_root', 2, 'service', '-inf', 'after_create',
            None, '2014-02-22 00:00', '2014-02-22 0:00', '2024-01-02 0:00', timedelta()),
        (None, 0, 'category', str, 'after_create',
            ValueError, None, None, None, None),
        ('no_root', 3, 'data', '+year', 'on_creating',
            None, '2013-07-16 12:30', '2013-07-16 12:30', '2013-07-16 12:30', timedelta()),
        ('root', 1, 'category', '-year', 'after_create',
            ValueError, None, None, None, None),
        ('no_root', 3, 'data', '-inf', 'on_creating',
            None, '2002-09-06 12:30', '2002-09-06 12:30', '2002-09-06 12:30', timedelta()),
        (None, 0, 'category', '-year', 'after_create',
            ValueError, None, None, None, None),
        ('no_root', 3, 'category', '-hour', 'after_create',
            ValueError, None, None, None, None),
        (None, 0, 'category', '-inf', 'on_creating',
            ValueError, None, None, None, None),
        ('root', 1, 'data', '-inf', 'on_creating',
            None, '2002-09-06 12:30', None, None, None),
        ('no_root', 2, 'data', str, 'on_creating',
            EntityFieldInvalid, None, None, None, None),
        ('root', 1, 'category', '+inf', 'after_create',
            ValueError, None, None, None, None),
    ]


def checked_change_provider():
    return [
        ('no_root', 3, 'service', 'no_leader', False, 'leader', True, None, False, True),
        ('no_root', 2, 'service', 'leader', True, 'no_leader', False, None, False, True),
        ('root', 1, 'data', 'leader', False, 'leader', False, None, False, False),
        ('no_root', 3, 'data', 'no_leader', True, 'no_leader', True, None, True, False),
        ('no_root', 2, 'data', 'no_leader', True, 'leader', True, None, True, True),
        ('root', 1, 'category', 'no_leader', False, 'no_leader', True, None, True, False),
        (None, 0, 'category', 'no_leader', False, 'leader', False, AttributeError, None, None),
        ('no_root', 3, 'category', 'leader', True, 'leader', False, None, False, False),
        ('no_root', 2, 'category', 'leader', False, 'leader', True, None, False, True),
        ('root', 1, 'service', 'no_leader', True, 'no_leader', False, None, False, False),
        (None, 0, 'category', 'leader', True, 'no_leader', True, AttributeError, None, None),
    ]


def comments_change_provider():
    return [
        ('no_root', 2, 'data', "Я родился!", 'on_creating'),
        (None, 0, 'category', "Я", 'after_create'),
        (None, 0, 'category', "Я"*COMMENTS_MAX_CHARS, 'after_load'),
        ('no_root', 3, 'category', None, 'on_creating'),
        ('no_root', 2, 'service', None, 'after_load'),
        ('no_root', 3, 'data', "Я", 'after_load'),
        (None, 0, 'category', "", 'after_create'),
        ('root', 1, 'service', "Я родился!", 'after_create'),
        (None, 0, 'category', "Я родился!", 'after_load'),
        ('root', 1, 'data', "", 'on_creating'),
        ('no_root', 3, 'service', "Я родился!", 'after_create'),
        ('no_root', 2, 'service', "Я", 'on_creating'),
        ('no_root', 3, 'service', "", 'after_load'),
        ('no_root', 2, 'data', "Я"*ALIAS_MAX_CHARS, 'after_create'),
        ('no_root', 2, 'category', "", 'after_create'),
        ('root', 1, 'category', None, 'after_load'),
        ('root', 1, 'service', "Я"*ALIAS_MAX_CHARS, 'on_creating'),
        ('root', 1, 'service', "Я", 'on_creating'),
        ('no_root', 3, 'category', "Я"*ALIAS_MAX_CHARS, 'after_load'),
        (None, 0, 'category', None, 'after_create'),
        ('no_root', 2, 'data', None, 'after_load'),
    ]


def name_change_provider():
    return [
        ('no_root', 3, 'category', None, AttributeError),
        (None, 0, 'category', "Я родился!", AttributeError),
        ('no_root', 3, 'data', "Я родился!", AttributeError),
        ('root', 1, 'service', "Я родился!", None),
        (None, 0, 'category', "Я"*(NAME_MAX_CHARS + 1), AttributeError),
        ('root', 1, 'data', "Я", AttributeError),
        ('no_root', 2, 'data', None, AttributeError),
        (None, 0, 'category', None, AttributeError),
        ('no_root', 3, 'service', "Я"*(NAME_MAX_CHARS+1), EntityFieldInvalid),
        ('no_root', 3, 'service', "Я"*NAME_MAX_CHARS, None),
        ('no_root', 2, 'category', "", AttributeError),
        ('no_root', 2, 'service', "Я", None),
        ('no_root', 2, 'category', "Я родился!", AttributeError),
        ('no_root', 3, 'category', "Я", AttributeError),
        ('root', 1, 'data', "Я"*(NAME_MAX_CHARS+1), AttributeError),
        (None, 0, 'category', "", AttributeError),
        ('no_root', 2, 'category', "Я"*(NAME_MAX_CHARS+1), AttributeError),
        ('root', 1, 'data', "", AttributeError),
        ('no_root', 3, 'service', "", None),
        ('root', 1, 'service', None, None),
        (None, 0, 'category', "Я", AttributeError),
        ('root', 1, 'category', "Я родился!", AttributeError),
    ]


def base_directory_provider():
    return [
        ('no_root', 3, 'category', "Я родился!", None),
        ('no_root', 2, 'data', None, AttributeError),
        (None, 0, 'category', None, EntityFieldInvalid),
        (None, 0, 'category', "Я", None),
        ('root', 1, 'data', "Я", AttributeError),
        ('no_root', 3, 'service', None, AttributeError),
        ('no_root', 3, 'data', "Я"*256, AttributeError),
        ('no_root', 2, 'service', "Я родился!", AttributeError),
        ('no_root', 2, 'category', "Я"*256, None),
        ('no_root', 2, 'category', "Я родился!", None),
        (None, 0, 'category', "Я"*256, None),
        ('no_root', 2, 'data', "Я"*257, AttributeError),
        ('root', 1, 'service', "", AttributeError),
        ('no_root', 3, 'category', "", None),
        (None, 0, 'category', "", None),
        ('root', 1, 'data', "Я родился!", AttributeError),
        ('no_root', 2, 'data', "", AttributeError),
        ('root', 1, 'category', None, None),
        ('no_root', 3, 'service', "Я"*257, AttributeError),
        ('no_root', 3, 'service', "Я"*256, AttributeError),
        (None, 0, 'category', "Я"*257, EntityFieldInvalid),
        ('no_root', 2, 'data', "Я", AttributeError),
        ('root', 1, 'service', "Я"*256, AttributeError),
        ('root', 1, 'category', "Я"*257, EntityFieldInvalid),
    ]
