import {translate as t} from '../../utils.mjs';
import DialogBox from '../base/DialogBox.jsx';


export default class UserAddBox extends DialogBox{

	get title(){
		return t("Add User");
	}

	renderContent(){
		return (
			<div style={{padding: "24px 16px"}}>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

				<p>Sed id semper risus in hendrerit gravida. Ipsum dolor sit amet consectetur adipiscing. Orci sagittis eu volutpat odio facilisis mauris sit amet massa. Hendrerit gravida rutrum quisque non tellus orci ac. Laoreet sit amet cursus sit amet dictum sit amet justo. Ipsum a arcu cursus vitae congue mauris. Pharetra diam sit amet nisl suscipit adipiscing bibendum est. Nibh sit amet commodo nulla. Duis at tellus at urna condimentum mattis pellentesque. Tristique risus nec feugiat in fermentum posuere urna. Eget aliquet nibh praesent tristique magna sit amet purus. Viverra accumsan in nisl nisi scelerisque eu ultrices vitae. Enim ut tellus elementum sagittis vitae. Convallis tellus id interdum velit laoreet id donec ultrices. Commodo nulla facilisi nullam vehicula ipsum a arcu cursus vitae. Ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Enim diam vulputate ut pharetra sit amet aliquam.</p>

				<p>Mattis ullamcorper velit sed ullamcorper morbi. Accumsan tortor posuere ac ut consequat semper viverra nam libero. Amet mattis vulputate enim nulla aliquet porttitor. Luctus accumsan tortor posuere ac. Scelerisque fermentum dui faucibus in ornare quam viverra orci sagittis. Eget felis eget nunc lobortis mattis. Arcu cursus vitae congue mauris rhoncus aenean vel. Nibh nisl condimentum id venenatis a condimentum. Blandit massa enim nec dui nunc mattis. Amet dictum sit amet justo donec. Non sodales neque sodales ut etiam sit amet nisl. Nisl condimentum id venenatis a. Sem integer vitae justo eget magna fermentum iaculis eu. Ac odio tempor orci dapibus ultrices in. Amet venenatis urna cursus eget nunc.</p>

				<p>Lectus quam id leo in vitae turpis massa. Habitant morbi tristique senectus et netus. Nibh ipsum consequat nisl vel pretium lectus quam id leo. Ultrices eros in cursus turpis massa tincidunt. Id consectetur purus ut faucibus pulvinar elementum integer enim. Condimentum id venenatis a condimentum. Malesuada nunc vel risus commodo viverra maecenas accumsan lacus. Nisi quis eleifend quam adipiscing vitae proin sagittis. Varius sit amet mattis vulputate enim nulla. Ipsum dolor sit amet consectetur adipiscing elit pellentesque habitant. In massa tempor nec feugiat nisl. Amet porttitor eget dolor morbi non arcu risus quis varius. Duis at tellus at urna condimentum mattis pellentesque id nibh. Fringilla urna porttitor rhoncus dolor purus.</p>

				<p>Praesent semper feugiat nibh sed pulvinar proin gravida hendrerit. Amet venenatis urna cursus eget nunc scelerisque. Tortor consequat id porta nibh venenatis cras. Tristique senectus et netus et malesuada fames ac turpis egestas. Ornare aenean euismod elementum nisi. Dolor morbi non arcu risus. Pretium nibh ipsum consequat nisl vel. Leo urna molestie at elementum eu facilisis sed. Sodales ut eu sem integer vitae. Quis enim lobortis scelerisque fermentum. Tristique senectus et netus et malesuada fames ac turpis. Arcu vitae elementum curabitur vitae nunc sed velit. Neque laoreet suspendisse interdum consectetur. Dapibus ultrices in iaculis nunc sed augue lacus viverra. Sapien pellentesque habitant morbi tristique senectus et netus. Vivamus arcu felis bibendum ut. Curabitur vitae nunc sed velit dignissim sodales.</p>

				<p>Tempor orci dapibus ultrices in iaculis nunc sed. Euismod nisi porta lorem mollis. In hac habitasse platea dictumst vestibulum rhoncus est. Egestas fringilla phasellus faucibus scelerisque. Amet venenatis urna cursus eget nunc scelerisque viverra. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate. In aliquam sem fringilla ut morbi tincidunt. Aliquam nulla facilisi cras fermentum odio eu feugiat. Posuere lorem ipsum dolor sit amet consectetur adipiscing elit duis. Nec feugiat in fermentum posuere urna nec tincidunt praesent semper. Ullamcorper a lacus vestibulum sed arcu. Amet risus nullam eget felis eget nunc. A pellentesque sit amet porttitor eget dolor morbi. Orci nulla pellentesque dignissim enim sit. Leo in vitae turpis massa. Mattis nunc sed blandit libero volutpat. Ultrices vitae auctor eu augue ut lectus arcu bibendum at. Eu tincidunt tortor aliquam nulla facilisi cras.</p>

				<p>Nulla porttitor massa id neque aliquam. Ipsum suspendisse ultrices gravida dictum fusce ut placerat orci nulla. Tellus id interdum velit laoreet id donec ultrices tincidunt arcu. Viverra mauris in aliquam sem fringilla. In est ante in nibh mauris cursus mattis molestie. Lobortis elementum nibh tellus molestie. At imperdiet dui accumsan sit amet nulla facilisi morbi. Pellentesque pulvinar pellentesque habitant morbi tristique senectus. Ut consequat semper viverra nam libero justo laoreet. Aliquet nibh praesent tristique magna sit amet purus gravida quis. Ornare massa eget egestas purus viverra accumsan in nisl nisi. At volutpat diam ut venenatis tellus in. Id ornare arcu odio ut sem nulla. Imperdiet sed euismod nisi porta. Lorem ipsum dolor sit amet consectetur adipiscing elit ut aliquam.</p>

				<p>Cras semper auctor neque vitae tempus quam. Ullamcorper malesuada proin libero nunc. Mattis vulputate enim nulla aliquet porttitor. Nisl nisi scelerisque eu ultrices vitae auctor eu augue. Feugiat in fermentum posuere urna. Blandit aliquam etiam erat velit scelerisque in dictum non consectetur. Nunc sed blandit libero volutpat sed cras ornare arcu dui. Et tortor consequat id porta. Viverra adipiscing at in tellus integer. Dolor morbi non arcu risus quis varius. Duis at consectetur lorem donec massa sapien faucibus et molestie. Senectus et netus et malesuada fames ac turpis egestas sed.</p>

				<p>Ultricies leo integer malesuada nunc vel risus commodo viverra. Etiam erat velit scelerisque in dictum non. Pretium nibh ipsum consequat nisl vel pretium lectus quam. Et odio pellentesque diam volutpat commodo sed egestas. Justo eget magna fermentum iaculis eu non diam. Varius duis at consectetur lorem donec massa sapien. Vitae semper quis lectus nulla at volutpat diam ut venenatis. Nisi lacus sed viverra tellus in hac. At elementum eu facilisis sed. Enim blandit volutpat maecenas volutpat blandit. Eros in cursus turpis massa tincidunt dui. Diam sit amet nisl suscipit. Porttitor leo a diam sollicitudin tempor. Id leo in vitae turpis massa sed elementum tempus egestas. Nunc scelerisque viverra mauris in. Ut venenatis tellus in metus vulputate. Quis vel eros donec ac odio. Et tortor at risus viverra adipiscing at in. Bibendum enim facilisis gravida neque convallis a cras semper auctor.</p>

				<p>Pellentesque adipiscing commodo elit at imperdiet dui. Mi in nulla posuere sollicitudin aliquam ultrices sagittis orci a. Non pulvinar neque laoreet suspendisse interdum consectetur libero. Cursus metus aliquam eleifend mi in nulla posuere. Odio morbi quis commodo odio aenean sed adipiscing diam. At risus viverra adipiscing at in. Pharetra pharetra massa massa ultricies mi quis. Pulvinar elementum integer enim neque. Amet nisl purus in mollis nunc sed id semper risus. Mi ipsum faucibus vitae aliquet nec ullamcorper sit amet. Diam donec adipiscing tristique risus nec feugiat in fermentum posuere. Vel eros donec ac odio tempor orci dapibus. In fermentum posuere urna nec tincidunt praesent. Volutpat commodo sed egestas egestas. Nulla facilisi nullam vehicula ipsum. Mi ipsum faucibus vitae aliquet. Netus et malesuada fames ac turpis egestas integer. Nisi vitae suscipit tellus mauris. Lacus sed viverra tellus in hac habitasse platea dictumst. Scelerisque felis imperdiet proin fermentum leo vel.</p>

				<p>Fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien nec. Dolor sed viverra ipsum nunc aliquet bibendum. Nullam ac tortor vitae purus faucibus. Eget felis eget nunc lobortis mattis. Aenean sed adipiscing diam donec. Varius morbi enim nunc faucibus a. Pharetra sit amet aliquam id diam. Facilisis mauris sit amet massa vitae tortor. Vitae elementum curabitur vitae nunc sed velit dignissim sodales ut. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum tellus. Proin sagittis nisl rhoncus mattis rhoncus urna neque viverra. Tellus in hac habitasse platea dictumst. Integer feugiat scelerisque varius morbi enim nunc faucibus. Nunc congue nisi vitae suscipit. Cursus euismod quis viverra nibh cras pulvinar mattis nunc sed. Consequat ac felis donec et odio pellentesque diam volutpat commodo. Facilisis magna etiam tempor orci eu lobortis elementum nibh tellus.</p>

				<p>In arcu cursus euismod quis viverra nibh cras pulvinar mattis. Imperdiet massa tincidunt nunc pulvinar. Sagittis orci a scelerisque purus semper. Risus commodo viverra maecenas accumsan. Consequat semper viverra nam libero justo laoreet sit amet cursus. Quisque id diam vel quam. Vulputate ut pharetra sit amet. Velit laoreet id donec ultrices tincidunt. Diam sollicitudin tempor id eu nisl nunc mi ipsum. Dolor magna eget est lorem ipsum dolor sit amet consectetur. Ultrices in iaculis nunc sed augue lacus. Urna nunc id cursus metus aliquam eleifend mi. Arcu cursus euismod quis viverra nibh cras. Duis at tellus at urna condimentum mattis. Proin libero nunc consequat interdum. Eros in cursus turpis massa tincidunt dui ut ornare. Purus in massa tempor nec feugiat nisl pretium fusce. Elementum sagittis vitae et leo duis ut. Tortor pretium viverra suspendisse potenti nullam ac. Vestibulum lectus mauris ultrices eros in cursus.</p>

				<p>Convallis convallis tellus id interdum velit laoreet. Cursus mattis molestie a iaculis at erat pellentesque adipiscing commodo. Enim lobortis scelerisque fermentum dui faucibus in ornare quam viverra. Ut eu sem integer vitae justo eget magna. Massa tempor nec feugiat nisl pretium fusce id. Tincidunt id aliquet risus feugiat in. Vulputate odio ut enim blandit volutpat maecenas volutpat blandit. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Nisi vitae suscipit tellus mauris a. Malesuada fames ac turpis egestas sed tempus urna. Vivamus arcu felis bibendum ut. At imperdiet dui accumsan sit. Scelerisque fermentum dui faucibus in.</p>

				<p>Enim eu turpis egestas pretium aenean pharetra. Vel pretium lectus quam id leo. A diam maecenas sed enim ut sem viverra. At varius vel pharetra vel turpis. Tortor at auctor urna nunc id cursus metus aliquam. Sit amet nulla facilisi morbi tempus iaculis urna id volutpat. Lorem sed risus ultricies tristique nulla aliquet enim tortor at. At tempor commodo ullamcorper a lacus vestibulum sed arcu non. Viverra aliquet eget sit amet tellus cras adipiscing enim eu. Sit amet mattis vulputate enim. Lacus suspendisse faucibus interdum posuere lorem. In metus vulputate eu scelerisque. Accumsan in nisl nisi scelerisque. Ornare lectus sit amet est placerat in egestas erat. Vel pharetra vel turpis nunc eget lorem dolor sed viverra. Ut tortor pretium viverra suspendisse potenti nullam. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida neque. In fermentum posuere urna nec tincidunt praesent. Felis bibendum ut tristique et.</p>

				<p>Laoreet id donec ultrices tincidunt arcu non. Convallis posuere morbi leo urna molestie. Fringilla est ullamcorper eget nulla facilisi etiam dignissim. Sed viverra tellus in hac habitasse platea dictumst. Arcu dictum varius duis at consectetur lorem. Aliquam vestibulum morbi blandit cursus risus. Netus et malesuada fames ac turpis egestas integer. Vivamus arcu felis bibendum ut tristique et egestas quis ipsum. Dolor sed viverra ipsum nunc aliquet bibendum enim facilisis gravida. Etiam sit amet nisl purus in. Sapien et ligula ullamcorper malesuada. At tellus at urna condimentum mattis pellentesque id nibh. Eu feugiat pretium nibh ipsum consequat. Mauris ultrices eros in cursus turpis massa tincidunt dui. Elit sed vulputate mi sit amet mauris commodo.</p>

				<p>Sed vulputate mi sit amet mauris commodo quis. Nibh nisl condimentum id venenatis a condimentum vitae. Non consectetur a erat nam at lectus urna. Quis lectus nulla at volutpat diam. Commodo odio aenean sed adipiscing diam donec. Sed turpis tincidunt id aliquet risus feugiat. Sagittis id consectetur purus ut faucibus pulvinar elementum. Turpis cursus in hac habitasse platea dictumst quisque. Id porta nibh venenatis cras sed felis eget velit. Eget nunc lobortis mattis aliquam faucibus. Vel pretium lectus quam id leo in vitae. Habitant morbi tristique senectus et netus. Arcu non sodales neque sodales ut. In fermentum posuere urna nec tincidunt.</p>

				<p>Ut venenatis tellus in metus vulputate eu. Phasellus vestibulum lorem sed risus ultricies. Et tortor consequat id porta nibh. Eu non diam phasellus vestibulum lorem sed. Faucibus ornare suspendisse sed nisi lacus. Pulvinar proin gravida hendrerit lectus a. Vel pharetra vel turpis nunc eget lorem dolor. Sed faucibus turpis in eu. Dui id ornare arcu odio. Tortor pretium viverra suspendisse potenti nullam ac tortor. Mi sit amet mauris commodo. Mi in nulla posuere sollicitudin aliquam ultrices sagittis orci a. Tristique magna sit amet purus gravida quis. Pharetra diam sit amet nisl suscipit adipiscing bibendum. Sed odio morbi quis commodo odio aenean sed. Ullamcorper morbi tincidunt ornare massa eget egestas purus. Tempus iaculis urna id volutpat lacus laoreet non. Et netus et malesuada fames ac turpis egestas. Cras ornare arcu dui vivamus arcu felis. Id ornare arcu odio ut sem nulla.</p>

				<p>Vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt. Urna cursus eget nunc scelerisque viverra mauris. Quisque id diam vel quam elementum pulvinar etiam non. Scelerisque viverra mauris in aliquam sem fringilla ut morbi. Pharetra vel turpis nunc eget lorem dolor sed. Tincidunt arcu non sodales neque sodales. Dui id ornare arcu odio ut sem. A cras semper auctor neque. Metus vulputate eu scelerisque felis. Facilisi nullam vehicula ipsum a arcu. Vel facilisis volutpat est velit egestas dui id. Pellentesque sit amet porttitor eget dolor morbi. Dictumst vestibulum rhoncus est pellentesque. Nec ultrices dui sapien eget.</p>

				<p>Nibh tellus molestie nunc non blandit massa enim. Tellus mauris a diam maecenas sed enim. Pellentesque elit eget gravida cum sociis natoque penatibus et magnis. Augue neque gravida in fermentum et sollicitudin ac orci phasellus. Enim blandit volutpat maecenas volutpat blandit aliquam. Nunc pulvinar sapien et ligula. Velit sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Suspendisse sed nisi lacus sed viverra tellus. Egestas congue quisque egestas diam in arcu cursus. Maecenas pharetra convallis posuere morbi leo urna molestie at elementum. Nec nam aliquam sem et tortor consequat id porta.</p>

				<p>Nec sagittis aliquam malesuada bibendum. Consequat semper viverra nam libero justo laoreet. Ut eu sem integer vitae justo eget magna fermentum iaculis. Odio morbi quis commodo odio aenean sed adipiscing. Arcu vitae elementum curabitur vitae nunc sed velit dignissim. Porta non pulvinar neque laoreet suspendisse interdum consectetur. Mauris rhoncus aenean vel elit scelerisque. Lorem donec massa sapien faucibus et molestie ac feugiat sed. Tellus cras adipiscing enim eu turpis egestas pretium. Amet nulla facilisi morbi tempus.</p>
			</div>
		);
	}

}